version: '3.9'

services:
  client:
    container_name: irc_client
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8200:80"  # Frontend served on host port 8200
    depends_on:
      - server
    restart: unless-stopped

  server:
    container_name: irc_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3550:3550"
    environment:
      - PORT=3550
    restart: unless-stopped


